# Camera Information for: cam0
# Generated at startup by DataRecorderNode
# Timestamp: 1762248906505617591

camera_name: "cam0"

pose:
  position:
    x: -0.643856
    y: 0.322439
    z: -1.65819
  orientation:
    w: 0.3029
    x: -0.00685349
    y: 0.00163991
    z: 0.952996

fov_degrees: 140

distortion_coefficients:
  data: [0, 0, 0, 0, 0]

cinemairsim:
  focal_length_mm: 4.323967
  field_of_view: "Current Field Of View:
	Horizontal Field Of View: 140;
	 Vertical Field Of View: 114.19"
  filmback_settings: "Name: 16:9 Digital Film;
	 Sensor Width: 23.76; 	 Sensor Height: 13.365
	 Sensor Aspect Ratio: 1.77778"
  lens_settings: "Name: Universal Zoom;
	 MinFocalLength: 4; 	 MaxFocalLength: 1000
	 Min FStop: 1.2; 	 Max Fstop: 22
	 Diaphragm Blade Count: 7
	 Minimum focus distance: 15"
  focus_distance: 100000.000000
  focus_aperture: 2.800000

metadata:
  vehicle_name: ""
  host_ip: "10.42.0.244"
  host_port: 41451
